mcabbott/AxisKeys.jl

src/selectors.jl, test/_packages.jl
This avoids this error: `MethodError: no method matching abs2(::Millisecond)`
=> support using Near selector on a time axis

src/functions.jl
I just realised this was crashing for me because I'm on julia master, and this was added:
https://github.com/JuliaLang/julia/pull/34048
No harm adding it now, will be needed anyway.
=> Added missing kwargs to mapreduce

Project.toml, README.md, src/AxisKeys.jl, src/fft.jl, test/_packages.jl
```julia
using AxisKeys, FFTW, Unitful
using Unitful: s
times = 0.1s:0.1s:10s
data = rand(100) ./ 10; data[1:5:end] .= 1;
A = KeyedArray(data, times)
Atil = fftshift(fft(A))
using Plots, UnitfulRecipes
plot(axiskeys(Atil,1), abs.(parent(Atil)))
```
Todo:
=> Support for FFT

src/functions.jl, test/_functions.jl
=> Add eachslice

README.md, src/tables.jl, test/_packages.jl, test/runtests.jl
We have two main use cases for this:
1. Wanting to construct KeyedArrays from adhoc DataFrames
2. Wanting to populate a pre-allocated Array from LibPQ.jl results. For example, we know how many timestamps, locations, ids, etc we expect to get back from our DB. 
We've been doing this internally for AxisArrays for a while, but never got around to open sourcing it.
=> Add support for KeyedArrays as a Tables sink

README.md
This was slightly misleading, the syntax  is more flexible and can be pretty similar to yours now, except the brackets. You can just use symbols. I'll put a link to this package in DD as well.
=> Fix DimensionalData.jl syntax ecample

Project.toml, src/AxisKeys.jl, src/functions.jl, src/names.jl, src/statsbase.jl, test/_packages.jl
This PR doesn't wrap everything, but it wraps most of the main weighted functions that we use at Invenia. Closes #26
=> Add support for weighted StatsBase methods

src/functions.jl, test/_functions.jl
Just extracts the numeric dim with the base `selectdim` call. Same as what NamedDims.jl does [here](https://github.com/invenia/NamedDims.jl/blob/942bb283c62dd64c0ca484bda19c1bb832f268fa/src/functions_dims.jl#L17).
=> Add a selectdim wrapper

Project.toml, src/functions.jl, test/_functions.jl
Fixed #43 
I note that later in the file for `mean`, `std`, `var` the same thing is true, but idk if it matters in those cases,
and I don't have easy MWE.
I can make follow ups for these, but I would like to get this one merged and released ASAP as it is breaking my code
=> make mapreduce pass on kwargs

src/lookup.jl, test/_findrange.jl
Before this change findindex(2:4, 2:5) returned a materialized array.
=> indexing a range with a range produces another range

Project.toml, src/wrap.jl, test/_packages.jl
The dimension names given to `NamedDimsArray` should be symbols. If we're converting from a `NamedArray`, then we can't guarantee that `.dimnames` will be a tuple of symbols — in practice I've come across code where they are strings, and for these cases `wrapdims` fails.
This change attempts to convert the dimnames to Symbols.
=> Convert NamedArray dimnames to Symbol

src/names.jl, src/push.jl, src/show.jl
Warning: use values(kwargs) and keys(kwargs) instead of kwargs.data and kwargs.itr
Comes from https://github.com/JuliaLang/julia/pull/39448
=> fix warning on julia 1.7

src/show.jl
To fix #77.
`ShowWith` is an AbstractString, and from https://discourse.julialang.org/t/what-is-the-interface-of-abstractstring/8937/4 it seems that `ncodeunits` is a required method for it. But apparently this is only really needed from 1.7 onwards.
Does this look right? It seems to print alright, with unicode key names as well:
```julia
julia> using AxisKeys
julia> data = rand(Int8, 2,10,3) .|> abs;
julia> A = KeyedArray(data; channel=[:αααααααααααααααααα, :right], time=range(13, step=2.5, length=10), iter=31:33)
3-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   channel ∈ 2-element Vector{Symbol}
→   time ∈ 10-element StepRangeLen{Float64,...}
□   iter ∈ 3-element UnitRange{Int64}
And data, 2×10×3 Array{Int8, 3}:
[:, :, 1] ~ (:, :, 31):
(13.0)  (15.5)  (18.0)  (20.5)  (23.0) …
```
=> define ncodeunits for ShowWith

Project.toml, src/AxisKeys.jl, src/chainrules.jl, test/_chainrules.jl, test/runtests.jl
Essentially pair-programmed with @mzgubic.
Needed to add an `rrule` for `keyless_unname` for a downstream AD use-case.
=> Add ChainRule for `keyless_unname`

test/speed.jl
This symlink was incorrect and errored when trying to access it.
=> Fix test/speed.jl symlink

Project.toml
It was a non-breaking change: https://github.com/invenia/NamedDims.jl/pull/202/files#r937572855
=> NamedDims compat to 0.3

Project.toml, src/tables.jl, test/_packages.jl
There's a type stability issue which occurs in `Tables.columns` when the type of the keys are different on different axes.
I demonstrate that the problem exists, and that this PR fixes it. Not sure what kind of regression test would be optimal, but happy to add one / some if there's an obvious place to put them.
```julia
using AxisKeys, Tables
D1 = 2500;
D2 = 2500;
data = randn(D1, D2);
k1 = collect(1:D1);
k2 = Int32.(collect(1:D2));
X = KeyedArray(data; k1, k2);
@benchmark Tables.columns($X)
```
on master then output of benchmarking is
```julia
BenchmarkTools.Trial: 8 samples with 1 evaluation.
Range (min … max):  654.951 ms … 766.341 ms  ┊ GC (min … max):  8.84% … 17.49%
Time  (median):     696.806 ms               ┊ GC (median):    12.74%
Time  (mean ± σ):   704.700 ms ±  42.018 ms  ┊ …
```
=> Fix performance problem for `Tables.Columns(::KeyedArray)`

src/selectors.jl
This was motivated by the disappearance of `_maybetail` from `Base`,
which causes `AxisKeys` to not be compatible with v1.9. As it happens,
`safe_tail` is identical to `_maybetail`, thus, it would seem that the
latter was eliminated due to redundancy. Inspection of the v1.6
branch of JuliaLang confirms that `safe_tail` exists in its same form,
thus, given the `[compat]` for this `AxisKeys`, this seems like a
harmless change which enables compatibility with `master`.
=> Replace `_maybetail` with `safe_tail`

Project.toml, src/tables.jl, test/_packages.jl
Resolve performance issues associated with type instabilities in tables without types columns (e.g. DataFrames) by introducing a function barrier.
=> Make wrapdims more performant

Project.toml, src/broadcast.jl, test/_basic.jl
Closes #128 
This is the same thing we're doing in NamedDims.jl here 
https://github.com/invenia/NamedDims.jl/blob/master/src/broadcasting.jl#L30
Working example output:
```
julia> using Revise, AxisKeys, LinearAlgebra
[ Info: Precompiling AxisKeys [94b1ba4f-4ee9-5380-92f1-94cde586c3c5]
julia> σ = wrapdims(rand(10); time=-5:5)
┌ Warning: range -5:5 replaced by -5:4, to match size(A, 1) == 10
└ @ AxisKeys ~/repos/invenia/AxisKeys.jl/src/wrap.jl:72
1-dimensional KeyedArray(NamedDimsArray(...)) with keys:
↓   time ∈ 10-element UnitRange{Int64}
And data, 10-element Vector{Float64}:
(-5)  0.7062162964371984
(-4)  0.7932003097802828
(-3)  0.3350060730546587
(-2)  0.9305918994338884
(-1)  0.4487008300540162
(0)  0.2893126114180271
(1)  0.22276748390348022
(2)  0.8940313473571855
(3) …
```
=> Fix #128 broadcast ambiguities

Project.toml, src/AxisKeys.jl, src/names.jl, test/_basic.jl
I decided to go with pairs vs kwargs because:
1. I wanted to support unnamed dims
2. The nested pair syntax of `oldname => newname => newvalues` seemed more intuitive than mixing pairs and kwargs.
Closes #60
=> Support rekeying a KeyedArray

Project.toml, src/functions.jl, test/_functions.jl
Closes https://github.com/mcabbott/AxisKeys.jl/issues/136
`Base.empty!` does not seem to be defined on general `Array`s, so this PR only extends the method  for keyed vectors.
=> Add method `Base.emtpy!(::KeyedVector)`

src/stack.jl, src/statsbase.jl
=> remove deprecated `VarArg{<:...}`

src/functions.jl, src/selectors.jl, src/stack.jl, test/_basic.jl, test/_functions.jl, test/_packages.jl, test/runtests.jl
- add new: Base.stack for keyed arrays
- update to match 1.9: Base.uncolon and Base.eachslice
=> fixes and updates for Julia 1.9

src/statsbase.jl
I missed this in my previous version.
=> remove last `Vararg{<:...`

Project.toml
Not sure if tests pass but as the breaking change was minimal IIRC (weighted sampling errors now if any weight is `NaN`) I think chances are high they will.
On a side note, this update went unnoticed since the CompatHelper action fails.
=> Add support for StatsBase 0.34

.github/workflows/ci.yml, Project.toml, ext/AbstractFFTsExt.jl, ext/ChainRulesCoreExt.jl, ext/CovarianceEstimationExt.jl, ext/InvertedIndicesExt.jl, ext/LazyStackExt.jl, ext/OffsetArraysExt.jl, ext/StatisticsExt.jl, ext/StatsBaseExt.jl, src/AxisKeys.jl, src/functions.jl, src/selectors.jl, src/show.jl, src/wrap.jl
Closes https://github.com/mcabbott/AxisKeys.jl/issues/150.
I got so used to AxisKeys bringing lots of these packages as dependencies, didn't even think that with 1.9 they can be made optional :) Only noticed after seeing the recent issue opened here.
Tests _(should)_ pass on both 1.6 and 1.9. Failures on 1.10 unrelated: there's a known Julia issue with new ambiguities https://github.com/JuliaLang/julia/issues/52386 https://github.com/JuliaLang/julia/issues/52263 https://github.com/JuliaSparse/SparseArrays.jl/issues/431.
=> turn most deps into weakdeps

test/_functions.jl
This test will fail on Julia 1.9+ until https://github.com/JuliaLang/julia/issues/53113 is resolved. The idea is mostly to enable PkgEval to catch this earlier.
=> add tests for sorting with non int eltypes
